project:
  type: website

website:
  title: "Zheng (Quinn) Wang"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Resources
        href: resources.qmd

format:
  html:
    theme: litera
    page-layout: full
    css: styles.css
